version: "3"
services:
  gremlin:
    build:
      context: "."
      dockerfile: Dockerfile-gremlin
    expose:
      - "8182"
  gremlex:
    links:
      - gremlin
    build:
      context: ../
      dockerfile: Dockerfile
    entrypoint: ./docker-compose/test-entrypoint.sh
    environment:
      - GREMLEX_HOST=gremlin
    depends_on:
      - gremlin
    volumes:
      - ../:/app
